<?php
$modversion['name'] = "¨Á¨ÊPI¸¹½Xµn¿ý";
$modversion['version'] = 1.00;
$modversion['description'] = "PI¸¹½Xµn¿ý";
$modversion['credits'] = "Modified by wanderer<br>( http://www.mpn-tw.com/ ) <br>Based on MyLinks by Kazumi Ono<br>( http://www.mywebaddons.com/ )<br>The XOOPS Project";
$modversion['help'] = "mydownloads.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/ICON3.gif";
$modversion['dirname'] = "Pinum";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "mydownloads_broken";
//$modversion['tables'][1] = "mydownloads_cat";
//$modversion['tables'][2] = "mydownloads_downloads";
//$modversion['tables'][3] = "mydownloads_mod";
//$modversion['tables'][4] = "mydownloads_text";
//$modversion['tables'][5] = "mydownloads_votedata";

// Admin things
//$modversion['hasAdmin'] = 0;
//$modversion['adminindex'] = "home.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Blocks
//$modversion['blocks'][1]['file'] = "index.php";
//$modversion['blocks'][1]['name'] = _MI_MYDOWNLOADS_BNAME1;
//$modversion['blocks'][1]['description'] = "Shows recently added donwload files";
//$modversion['blocks'][1]['show_func'] = "b_mydownloads_top_show";
//$modversion['blocks'][1]['edit_func'] = "b_mydownloads_top_edit";
//$modversion['blocks'][1]['options'] = "date|10";
//$modversion['blocks'][2]['file'] = "mydownloads_top.php";
//$modversion['blocks'][2]['name'] = _MI_MYDOWNLOADS_BNAME2;
//$modversion['blocks'][2]['description'] = "Shows most downloaded files";
//$modversion['blocks'][2]['show_func'] = "b_mydownloads_top_show";
//$modversion['blocks'][2]['edit_func'] = "b_mydownloads_top_edit";
//$modversion['blocks'][2]['options'] = "hits|10";

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = "PI ¸¹½X¬d¸ß";
//$modversion['sub'][1]['url'] = "index.php?submit=search";
//$modversion['sub'][2]['name'] = _MI_MYDOWNLOADS_SMNAME2;
//$modversion['sub'][2]['url'] = "topten.php?hit=1";
//$modversion['sub'][3]['name'] = _MI_MYDOWNLOADS_SMNAME3;
//$modversion['sub'][3]['url'] = "topten.php?rate=1";

// Search
//$modversion['hasSearch'] = 1;
//$modversion['search']['file'] = "include/search.inc.php";
//$modversion['search']['func'] = "mydownloads_search";
?>