1308513215
return array (
  1 => 
  array (
    'name' => '系統管理',
    'dirname' => 'system',
    'content' => '<div class=\'module-menu-content\'><div><strong>快速連結</strong><ul><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=banners\' title=\'廣告管理\'>廣告管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=blocksadmin\' title=\'區塊管理\'>區塊管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=groups\' title=\'群組管理\'>群組管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=images\' title=\'圖片管理\'>圖片管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=modulesadmin\' title=\'模組管理\'>模組管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=preferences\' title=\'一般設定\'>一般設定</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=smilies\' title=\'表情管理\'>表情管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=userrank\' title=\'註冊會員等級\'>註冊會員等級</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=users\' title=\'編輯會員\'>編輯會員</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=findusers\' title=\'尋找會員\'>尋找會員</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=mailusers\' title=\'電子郵件群寄\'>電子郵件群寄</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=avatars\' title=\'圖像管理\'>圖像管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=tplsets\' title=\'樣板管理\'>樣板管理</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=comments\' title=\'評論管理\'>評論管理</a></li></ul></div><br /><div><a href=\'javascript: xoopsToggleDisplay("mb-1-desc")\' title=\'說明\'><img class=\'admin_layer_img\' src=\'http://localhost/xoops/modules/system/images/system_slogo.png\' alt=\'\' /> <span id=\'mb-1-desc-label\'>&raquo;</span></a></div><div id=\'mb-1-desc\' style=\'display: none;\'><strong>作者</strong><br /><br /><strong>版本</strong> - 2<br /><strong>說明</strong><br />管理、設定網站的核心選項</div></div>',
  ),
  2 => 
  array (
    'name' => '站內私人訊息',
    'dirname' => 'pm',
    'content' => '<div class=\'module-menu-content\'><div><strong>快速連結</strong><ul><li><a href=\'http://localhost/xoops/modules/pm/admin/admin.php\' title=\'模組首頁\'>模組首頁</a></li><li><a href=\'http://localhost/xoops/modules/pm/admin/prune.php\' title=\'清理資料\'>清理資料</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=preferences&amp;op=showmod&amp;mod=2\' title=\'基本參數設定\'>基本參數設定</a></li></ul></div><br /><div><a href=\'javascript: xoopsToggleDisplay("mb-2-desc")\' title=\'說明\'><img class=\'admin_layer_img\' src=\'http://localhost/xoops/modules/pm/images/logo.png\' alt=\'\' /> <span id=\'mb-2-desc-label\'>&raquo;</span></a></div><div id=\'mb-2-desc\' style=\'display: none;\'><strong>作者</strong><br />Jan Pedersen; Taiwen Jiang <phppp@users.sourceforge.net><br /><strong>版本</strong> - 1.02<br /><strong>說明</strong><br />用戶之間的私人訊息模組</div></div>',
  ),
  3 => 
  array (
    'name' => '用戶管理',
    'dirname' => 'profile',
    'content' => '<div class=\'module-menu-content\'><div><strong>快速連結</strong><ul><li><a href=\'http://localhost/xoops/modules/profile/admin/user.php\' title=\'用戶\'>用戶</a></li><li><a href=\'http://localhost/xoops/modules/profile/admin/category.php\' title=\'分類\'>分類</a></li><li><a href=\'http://localhost/xoops/modules/profile/admin/field.php\' title=\'欄位\'>欄位</a></li><li><a href=\'http://localhost/xoops/modules/profile/admin/step.php\' title=\'註冊步驟\'>註冊步驟</a></li><li><a href=\'http://localhost/xoops/modules/profile/admin/permissions.php\' title=\'權限\'>權限</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=preferences&amp;op=showmod&amp;mod=3\' title=\'基本參數設定\'>基本參數設定</a></li></ul></div><br /><div><a href=\'javascript: xoopsToggleDisplay("mb-3-desc")\' title=\'說明\'><img class=\'admin_layer_img\' src=\'http://localhost/xoops/modules/profile/images/logo.png\' alt=\'\' /> <span id=\'mb-3-desc-label\'>&raquo;</span></a></div><div id=\'mb-3-desc\' style=\'display: none;\'><strong>作者</strong><br />Jan Pedersen; Taiwen Jiang <phppp@users.sourceforge.net>; alfred <myxoops@t-online.de>; Wishcraft <simon@xoops.org><br /><strong>版本</strong> - 1.55<br /><strong>說明</strong><br />管理用戶訊息的模組</div></div>',
  ),
  4 => 
  array (
    'name' => 'Xoops Protector 防護模組',
    'dirname' => 'protector',
    'content' => '<div class=\'module-menu-content\'><div><strong>快速連結</strong><ul><li><a href=\'http://localhost/xoops/modules/protector/admin/index.php\' title=\'防護中心\'>防護中心</a></li><li><a href=\'http://localhost/xoops/modules/protector/admin/index.php?page=advisory\' title=\'安全建議\'>安全建議</a></li><li><a href=\'http://localhost/xoops/modules/protector/admin/index.php?page=prefix_manager\' title=\'前綴字串管理員\'>前綴字串管理員</a></li><li><a href=\'http://localhost/xoops/modules/system/admin.php?fct=preferences&amp;op=showmod&amp;mod=4\' title=\'基本參數設定\'>基本參數設定</a></li></ul></div><br /><div><a href=\'javascript: xoopsToggleDisplay("mb-4-desc")\' title=\'說明\'><img class=\'admin_layer_img\' src=\'http://localhost/xoops/modules/protector/module_icon.php\' alt=\'\' /> <span id=\'mb-4-desc-label\'>&raquo;</span></a></div><div id=\'mb-4-desc\' style=\'display: none;\'><strong>作者</strong><br />GIJ=CHECKMATE<br />PEAK Corp.(http://www.peak.ne.jp/)<br /><strong>版本</strong> - 3.4<br /><strong>說明</strong><br />此模組可保護您的XOOPS網站免於遭受各種攻擊，例如Dos阻斷攻擊、隱碼攻擊及各種污染</div></div>',
  ),
);
