<?php
$modversion['name'] = "阪京e化測試系統";
$modversion['version'] = "0.01beta";
$modversion['description'] = "e System Link";
$modversion['author'] = "cOOpEr Chen<br />( cooper@ozaki.com.tw )<br /> http://www.ozaki.com.tw/";
$modversion['credits'] = "The OZAKI Project";
//$modversion['help'] = "quotes.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "company_slogo.jpg";
$modversion['dirname'] = "esystem";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "products";
//$modversion['tables'][1] = "prodseries";
//$modversion['tables'][2] = "prodtype";

// Admin things
//$modversion['hasAdmin'] = 1;
//$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Blocks
//$modversion['blocks'][1]['file'] = "ShowProdList.php";
//$modversion['blocks'][1]['name'] = _MI_COMPANYDATA_BNAME1;
//$modversion['blocks'][1]['description'] = "Shows new products";
//$modversion['blocks'][1]['show_func'] = "b_showroom_show";

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = _COMPANYDATA_LIST;
//$modversion['sub'][1]['url'] = "ShowProdList.php";
//$modversion['sub'][2]['name'] = _WEBCAL_PRIVATE;
//$modversion['sub'][2]['url'] = "index.php?calendar=0";
?>